#!/usr/bin/env bash
# ~/.config/theme/folder-color.sh
#
# Sets the colour of every Papirus folder icon by generating a small icon
# theme, ~/.local/share/icons/Leonardita-Sunset-folders/, made only of
# symlinks that point at Papirus's own folder-<colour>-*.svg files. The
# hand-made overlay (Leonardita-Sunset) lists it first in Inherits, so
# Nemo, the file chooser and every GTK app pick the colour up without a
# single file under /usr/share being touched -- a Papirus package update
# cannot undo it.
#
# The generated theme is IGNORED by the dotfiles (~/.dotfiles_ignore); this
# script is the source of truth. After a restore, run it once.
#
# This is what the upstream `papirus-folders` tool does, except that tool
# rewrites /usr/share/icons/Papirus in place and needs a pacman hook to
# survive updates. Doing it in the overlay keeps it in the dotfiles.
#
# ─── USAGE ────────────────────────────────────────────────────────────────
#
#        ~/.config/theme/folder-color.sh carmine
#        ~/.config/theme/folder-color.sh --list       # colours Papirus ships
#        ~/.config/theme/folder-color.sh --reset      # back to Papirus default (blue)
#
#   Then press F5 in Nemo. GTK reads the overlay directory fresh (no
#   icon-theme.cache on purpose), so no restart is needed.
#
# ─── WHAT IT TOUCHES ──────────────────────────────────────────────────────
#
#   Only ~/.local/share/icons/Leonardita-Sunset-folders/. It never writes
#   into the hand-made Leonardita-Sunset theme. Safe to re-run; --reset
#   removes the generated theme entirely.
#
#   The sidebar is unaffected: Nemo draws it with its own xsi-* symbolic
#   set, recoloured from the GTK theme's foreground, not from Papirus.

set -e

PAPIRUS=/usr/share/icons/Papirus
OVERLAY="$HOME/.local/share/icons/Leonardita-Sunset-folders"
SIZES="16x16 22x22 24x24 32x32 48x48 64x64 128x128"

list_colours() {   # a colour is a name that has the full variant set, e.g. folder-<c>-documents
    ls "$PAPIRUS/48x48/places/" | sed -nE 's/^folder-([a-z]+)-documents\.svg$/\1/p' | sort | tr '\n' ' '; echo
}

remove_ours() {   # the whole generated theme is ours to delete
    [ -d "$OVERLAY" ] && rm -rf "$OVERLAY"
    return 0
}

write_index() {   # the generated theme's own index.theme, one section per size
    mkdir -p "$OVERLAY"
    {
        echo "[Icon Theme]"
        echo "Name=Leonardita-Sunset-folders"
        echo "Comment=GENERATED by ~/.config/theme/folder-color.sh -- do not edit, rerun the script. Papirus folder colour: $1"
        echo "Inherits=Papirus-Dark"
        echo "Directories=$(for s in $SIZES; do printf '%s/places,' "$s"; done | sed 's/,$//')"
        for s in $SIZES; do
            printf '\n[%s/places]\nSize=%s\nContext=Places\nType=Fixed\n' "$s" "${s%%x*}"
        done
    } > "$OVERLAY/index.theme"
}

case "${1:-}" in
    --list)  echo "Papirus folder colours:"; list_colours; exit 0 ;;
    --reset) remove_ours; echo "reset: generated theme removed, Papirus default (blue) applies"; exit 0 ;;
    "")      echo "usage: $0 <colour> | --list | --reset" >&2; exit 2 ;;
esac

colour="$1"
if [ ! -e "$PAPIRUS/48x48/places/folder-$colour-documents.svg" ]; then
    echo "no such Papirus folder colour: $colour" >&2
    echo "available:"; list_colours; exit 1
fi

remove_ours
write_index "$colour"
made=0
for s in $SIZES; do
    src="$PAPIRUS/$s/places"; dst="$OVERLAY/$s/places"
    [ -d "$src" ] || continue
    mkdir -p "$dst"
    # folder-<colour>.svg -> folder.svg ; folder-<colour>-X.svg -> folder-X.svg
    for f in "$src"/folder-"$colour".svg "$src"/folder-"$colour"-*.svg; do
        [ -e "$f" ] || continue
        name=$(basename "$f"); name="${name/-$colour/}"
        ln -sfn "$f" "$dst/$name"; made=$((made+1))
    done
    # user-<colour>-home.svg -> user-home.svg ; same for desktop
    for f in "$src"/user-"$colour"-*.svg; do
        [ -e "$f" ] || continue
        name=$(basename "$f"); name="${name/-$colour/}"
        ln -sfn "$f" "$dst/$name"; made=$((made+1))
    done
done
echo "folder colour: $colour  ($made links in $OVERLAY). Press F5 in Nemo."
